### ISSUE TITLE
Cosmic Desktop Issues

### ISSUE THREAD

**Issue by addy419** [lilyinstarlight/nixos-cosmic#57]
Hi Lily,

There are a few bugs and issues I've found in the cosmic desktop on NixOS. I'm not sure if these are NixOS specific issues or just not implemented in CosmicDE. but, I'd like to keep track of them here and keep this list updated as I find new ones. Please feel free to add your own issues to this list.

- [ ] Unable to change CPU governer (to High performance or power saving) with the cosmic-applet-battery
- [ ] Incorrect disk capacity in About page - 6.36TiB
- [ ] Desktop crashes when display turns off (Mine goes to power save after few hours). Resumes at login.
- [ ] Opening GOverlay VkBasalt tab crashes the desktop
- [ ] Cannot shift+delete in file manager, Cannot clear Trash (This is mostly unimplemented)
- [ ] Bluetooth (Audio)/WiFi do not provide any configuration options. Blueman/NM-applet required for now (Unimplemented)

**Comment by RAVENz46** [comment]
I found
- Some gtk apps cannot open link(e.g. newsflash).
![screenshot-2024-04-06-02-44-16](https://github.com/lilyinstarlight/nixos-cosmic/assets/86608952/f8b8115c-0768-41fb-94a3-5097b760fcb1)
- Volume mismatch between applet and OSD.

I have to check that popos has same issues or not.

**Comment by lilyinstarlight** [comment]
Apologies for not immediately getting back to this, but I think some of these things have been fixed in the meantime. Could you check if the following is working for you now?

- changing CPU governor with cosmic-applet-battery
- cosmic-files trash stuff
- bluetooth and wifi settings
- battery showing 0% when one is not present
- lock screen
- dock segments
- screenshot tool icons

Also yes, brightness slider will not work on desktop since monitor brightness cannot be controlled in most circumstances as far as I know

Currently cosmic-store does work with flatpak and I've been using it, it just only will use user remotes (e.g. do a `flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo` to add flathub if you want flatpaks from there)

Also @RAVENz46, can you share logs if changing power profiles using systemd76-power is still broken?

**Comment by addy419** [comment]
@lilyinstarlight , I updated cosmic an hour ago, but unfortunately, most of these aren't fixed.

* For 1 & 4, I am unable to start the battery-applet altogether.
* No Bluetooth or wifi settings in the settings page. I needed blueman to turn on the bluetooth as well, cosmic applet did not work for me. Also unable to change audio codec for headphones, blueman worked there as well (or pavucontrol)
* Still no icons in screenshot tool


*FIXED*
* cosmic files trash can be cleared now, but shift + delete does not work.
* lockscreen works
* dock fixed

**Comment by RAVENz46** [comment]
@lilyinstarlight 
Sorry for late.
It's still does not work for me.
<details>

<summary>applet log</summary>

```console
$ RUST_LOG=debug cosmic-applet-battery
2024-05-24T04:23:42.286841Z  INFO cosmic_applets: Starting `cosmic-applet-battery` with version 0.1.1
2024-05-24T04:23:42.286872Z DEBUG i18n_embed: Attempting to load language file: "en/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.286884Z DEBUG i18n_embed::fluent: Loaded language file: "en/cosmic_applet_battery.ftl" for language: "en"
2024-05-24T04:23:42.287194Z  INFO i18n_embed::requester: Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
2024-05-24T04:23:42.287204Z DEBUG i18n_embed: Selecting translations for domain "cosmic_applet_battery"
2024-05-24T04:23:42.287211Z DEBUG i18n_embed: Searching for available languages, found language file: "de/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287216Z DEBUG i18n_embed: Searching for available languages, found language file: "en/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287218Z DEBUG i18n_embed: Searching for available languages, found language file: "es-ES/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287219Z DEBUG i18n_embed: Searching for available languages, found language file: "fa/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287221Z DEBUG i18n_embed: Searching for available languages, found language file: "fi/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287223Z DEBUG i18n_embed: Searching for available languages, found language file: "fr/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287225Z DEBUG i18n_embed: Searching for available languages, found language file: "id/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287227Z DEBUG i18n_embed: Searching for available languages, found language file: "it/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287228Z DEBUG i18n_embed: Searching for available languages, found language file: "ja/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287230Z DEBUG i18n_embed: Searching for available languages, found language file: "nl/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287232Z DEBUG i18n_embed: Searching for available languages, found language file: "pl/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287236Z DEBUG i18n_embed: Searching for available languages, found language file: "pt/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287238Z DEBUG i18n_embed: Searching for available languages, found language file: "pt-BR/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287241Z DEBUG i18n_embed: Searching for available languages, found language file: "ru/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287243Z DEBUG i18n_embed: Searching for available languages, found language file: "sr-Cyrl/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287245Z DEBUG i18n_embed: Searching for available languages, found language file: "sr-Latn/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287247Z DEBUG i18n_embed: Searching for available languages, found language file: "uk/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287257Z DEBUG i18n_embed: Requested Languages: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
2024-05-24T04:23:42.287260Z DEBUG i18n_embed: Available Languages: [LanguageIdentifier { language: Language(Some("de")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("en")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("es")), script: None, region: Some(Region("ES")), variants: None }, LanguageIdentifier { language: Language(Some("fa")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("fi")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("fr")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("id")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("it")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("ja")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("nl")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("pl")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("pt")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("pt")), script: None, region: Some(Region("BR")), variants: None }, LanguageIdentifier { language: Language(Some("ru")), script: None, region: None, variants: None }, LanguageIdentifier { language: Language(Some("sr")), script: Some(Script("Cyrl")), region: None, variants: None }, LanguageIdentifier { language: Language(Some("sr")), script: Some(Script("Latn")), region: None, variants: None }, LanguageIdentifier { language: Language(Some("uk")), script: None, region: None, variants: None }]
2024-05-24T04:23:42.287270Z DEBUG i18n_embed: Supported Languages: [LanguageIdentifier { language: Language(Some("en")), script: None, region: None, variants: None }]
2024-05-24T04:23:42.287272Z DEBUG i18n_embed: Attempting to load language file: "en/cosmic_applet_battery.ftl"
2024-05-24T04:23:42.287275Z DEBUG i18n_embed::fluent: Loaded language file: "en/cosmic_applet_battery.ftl" for language: "en"
2024-05-24T04:23:42.288366Z DEBUG sctk: Bound new global [42] wl_seat v7
2024-05-24T04:23:42.288380Z DEBUG sctk: Bound new global [41] wl_output v4
2024-05-24T04:23:42.288383Z DEBUG sctk: Bound new global [6] zxdg_output_manager_v1 v3
2024-05-24T04:23:42.303222Z DEBUG sctk: Bound new global [1] wl_compositor v5
2024-05-24T04:23:42.303234Z DEBUG sctk: Bound new global [2] wl_subcompositor v1
2024-05-24T04:23:42.303237Z DEBUG sctk: Bound new global [16] wp_viewporter v1
2024-05-24T04:23:42.303239Z DEBUG sctk: Bound new global [15] wl_shm v1
2024-05-24T04:23:42.303243Z DEBUG sctk: Bound new global [38] zwp_linux_dmabuf_v1 v4
2024-05-24T04:23:42.304110Z DEBUG sctk: Bound new global [42] wl_seat v7
2024-05-24T04:23:42.306284Z DEBUG sctk: supported wl_shm format Abgr8888
2024-05-24T04:23:42.306289Z DEBUG sctk: supported wl_shm format Xbgr8888
2024-05-24T04:23:42.306292Z DEBUG sctk: supported wl_shm format Xrgb8888
2024-05-24T04:23:42.306295Z DEBUG sctk: supported wl_shm format Argb8888
2024-05-24T04:23:42.306311Z DEBUG sctk: supported wl_shm format Abgr8888
2024-05-24T04:23:42.306314Z DEBUG sctk: supported wl_shm format Xbgr8888
2024-05-24T04:23:42.306315Z DEBUG sctk: supported wl_shm format Xrgb8888
2024-05-24T04:23:42.306317Z DEBUG sctk: supported wl_shm format Argb8888
2024-05-24T04:23:42.306510Z DEBUG new:{}{task_name="org.freedesktop.UPower.PowerProfiles proxy caching"}: zbus::proxy: Failed to get owner of org.freedesktop.UPower.PowerProfiles: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UPower.PowerProfiles': no such name
2024-05-24T04:23:42.307650Z ERROR cosmic_applet_battery::app: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.90" (uid=1000 pid=3584 comm="cosmic-applet-battery" label="kernel") interface="com.system76.PowerDaemon" member="GetProfile" error name="(unset)" requested_reply="0" destination="com.system76.PowerDaemon" (uid=0 pid=1359 comm="/nix/store/4z7d10mlrl2fsn8z7kd6r5k0mnjhm7w0-system" label="kernel")
2024-05-24T04:23:42.307655Z ERROR cosmic_applet_battery::app: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower.PowerProfiles was no⏎          
```
</details>

I still only can change profile with `sudo system76-power profile <profile>`.

**Comment by jh-devv** [comment]
@lilyinstarlight 

I have these, some may be duplicated of @addy419's:
- https://github.com/pop-os/cosmic-screenshot/issues/18
- https://github.com/pop-os/cosmic-comp/issues/724
- #257
- #258 

Then, there are certain issues with the settings application, as for example:
- #254 
- Performance issues
- No Bluetooth + WiFi setting page
- Issues with refreshing when changing themes (seems to happen with all of the other cosmic applications too)

**Comment by amozeo** [comment]
> No lockscreen (Not sure if this is unimplemented)

lockscreen is implemented in cosmic and it doesn't work as of 7d3dd56cca20e409261ff8c69867d38376f7ecae

**Comment by lilyinstarlight** [comment]
> This seems to be fixed by removing the `xdg-desktop-portal-gtk` package from the `extraPortals`?
> Since, if you have both, `gtk` and cosmic `xdg` desktop agents running and since they provide some of the same API's, it doesn't really like that overlap?

Did you confirm it fixes it?

The overlap is already appropriately handled by the portal config preferring cosmic for any overlap. Also xdg-mime handling needs config changes for the xdg-desktop-portal portal, neither the cosmic nor gtk portals as far as I know

**Comment by lilyinstarlight** [comment]
> It has solved the url clinking not opening issue.

What specifically solved it?

**Comment by Thatoo** [comment]
Sorry, it isn't really clear to me.
Adding
`systemd.user.extraConfig = ''DefaultEnvironment="PATH=/run/wrappers/bin:/etc/profiles/per-user/%u/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin"'';`
solve my issue as explain in here https://github.com/lilyinstarlight/nixos-cosmic/issues/273.

**Comment by Thatoo** [comment]
@addy419 could you update your first post and if possible could you close this issue and open one issue for each one remaining?
